# Generated by Django 4.2 on 2024-05-16 00:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                ("updated_at", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "external_id",
                    models.CharField(max_length=60, verbose_name="External ID"),
                ),
                ("score", models.FloatField(default=1000, verbose_name="Score")),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Active"), (2, "Inactive")],
                        default=1,
                        verbose_name="Status",
                    ),
                ),
                ("preapproved_at", models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                "verbose_name": "Customer",
                "verbose_name_plural": "Customers",
            },
        ),
    ]
