# Generated by Django 3.1 on 2024-05-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_alter_loan_contract_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='external_id',
            field=models.CharField(max_length=60, unique=True, verbose_name='External ID'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
