# Generated by Django 4.2 on 2024-05-17 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("loan", "0002_alter_loan_contract_version"),
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PaymetDetail",
            new_name="PaymentDetail",
        ),
    ]
